[package]
name = "discord-irc"
version = "0.1.0"
authors = ["pbzweihander <pbzweihander@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
env_logger = "0.7.1"
futures = "0.3.1"
libconfig = { version = "0.10.1", package = "config" }
libirc = { version = "0.14.1", package = "irc" }
log = "0.4.8"
serde = "1.0.104"
tokio = { version = "0.2.25", features = ["macros", "rt-core"] }

[dependencies.serenity]
version = "0.10.2"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "http",
    "rustls_tokio_0_2_backend",
    "utils",
]
