[package]
name = "discord-irc"
version = "0.1.0"
authors = ["pbzweihander <pbzweihander@gmail.com>"]
edition = "2018"

[dependencies]
configc = { version = "0.10.1", package = "config" }
env_logger = "0.7.1"
encoding = "0.2.33"
failure = "0.1.6"
futures = "0.3.1"
log = "0.4.8"
serde = "1.0.104"
yaircc = "0.1.0"

[dependencies.async-std]
version = "1.8.0"
features = ["attributes", "tokio02"]

[dependencies.serenity]
version = "0.10.2"
default-features = false
features = [
    "builder",
    "cache",
    "client",
    "gateway",
    "model",
    "http",
    "rustls_tokio_0_2_backend",
    "utils",
]
