[irc]
server = ""
port = 6667
# password = ""
use_tls = true
username = ""
realname = ""
nickname = ""
channel = ""
ignores = []
# bridge_member_changes = false

# [irc.ozinger]
# authline = "id pw"

[discord]
token = ""
channel_id = 0
webhook_id = 0
webhook_token = ""
ignores = []
