[irc]
url = ""
username = ""
realname = ""
# password = ""
nickname = ""
channel = ""
ignores = []

# [irc.ozinger]
# authline = "id pw"

[discord]
token = ""
channel_id = 0
webhook_id = 0
webhook_token = ""
ignores = []
