on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --locked
      - run: cargo test --locked
      - run: cargo clippy --locked --no-deps -- -D warnings
      - run: cargo fmt -- --check
